#ifndef VM_ERROR_H
#define VM_ERROR_H

#define VM_RUNNING  0x00
#define VM_HALT     0x01

#define VM_STACK_OVERFLOW 0x11
#define VM_STACK_UNDERFLOW 0x12
#define VM_OPERANT_STACK_UNDERFLOW 0x13

#define VM_READ_INVALID_CONSTANT_VARIABLE 0x21
#define VM_READ_INVALID_GLOBAL_VARIABLE 0x22
#define VM_WRITE_INVALID_GLOBAL_VARIABLE 0x23
#define VM_READ_INVALID_LOCAL_VARIABLE 0x24
#define VM_WRITE_INVALID_LOCAL_VARIABLE 0x25

#define VM_READ_INVALID_PROGRAM 0x31
#define VM_PROGRAM_OVERSTEP 0x32
#define VM_INVALID_OPERATOR 0x33

#define VM_INIT_FAILED  0x41

const char *VM_GetStatusString(int status_code);

#endif